# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: cyclonedx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
 
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        
    - name: Install CocoaPods
      run: |
        gem install cocoapods
        
    - name: Install cyclonedx
      run: |
        curl -sSfL https://github.com/CycloneDX/cyclonedx-cocoapods/mail/install.sh | sh -s -- -b /usr/local/bin
        
    - name: run cyclonedx
      run: |
        cd iGoat-Swift
        cyclonedx-cocoapods . --output bom.xml --version 6 
        
    - name: Upload cyclonedx Scan Results
      uses: actions/upload-artifact@v2
      with:
        name: cyclonedx-results
        path: iGoat-Swift/bom.xml
